# Generated by Django 4.0 on 2021-12-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Password')),
                ('f_name', models.CharField(max_length=50, verbose_name='First name')),
                ('l_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('type', models.CharField(choices=[('user', 'Пользователь'), ('tutor', 'Преподаватель'), ('manager', 'Менеджер')], db_index=True, default='user', max_length=14, verbose_name='Тип пользователя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлена')),
                ('access', models.ManyToManyField(related_name='%(class)s_access', to='lessons.Lesson', verbose_name='Доступ к урокам')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
