# Generated by Django 4.0 on 2021-12-20 06:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0001_initial'),
        ('chat_ws', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='student',
        ),
        migrations.AddField(
            model_name='msg',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_student', to='users.user', verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='msg',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lesson', to='lessons.lesson', verbose_name='Предмет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='msg',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_oponent', to='users.user', verbose_name='Опонент'),
        ),
    ]
